### ISSUE TITLE
Date de dernier lancement du démon pas mise à jour

### ISSUE THREAD

**Issue by ChristopheHD** [mika-nt28/Jeedom-voletProp#146]
### Objectif de la manipulation
Voir les traces debug.
### Procédure de reproduction
Dans le panneau de configuration du plugin :
- Niveau de log debug
- Sauvegarder
- (Re)Démarrer le démon
### Résultat attendu
La date de dernier lancement du démon est mise à jour et des logs sont disponibles.
### Résultat constaté
La date de dernier lancement du démon n'est pas mise à jour et aucun log n'est disponible.
### Commentaire
Comme je n'arrive pas à activer les logs debug, je ne peux pas les joindre à cette demande.
Version du plugin : 2019-09-16 15:19:05
Version de Jeedom : 3.3.33

**Comment by mika-nt28** [comment]
Désolé du delais je n'ai pas vue ce poste
Je ne sais pas pourquoi je ne suis plus notifié

La mise a jours de cette date n'est pas gerer par le plugin mais par le core de jeedom
