### ISSUE TITLE
Pb démarrage plugin

### ISSUE THREAD

**Issue by Xav-74** [mika-nt28/Jeedom-voletProp#160]
Depuis quelques jours (difficile de mettre une date exacte et une action en face, type mise à jour Jeedom ou voletProp), j'ai cette erreur au démarrage de mon Jeedom :

`Erreur sur la fonction stop du plugin : Too few arguments to function voletProp::Stop(), 0 passed in /var/www/html/core/class/plugin.class.php on line 520 and exactly 1 expected`

Pas de problème avec le fonctionnement du plugin par contre.
A suivre donc.

Xavier

**Comment by mika-nt28** [comment]
Tester la beta pour validé la correction
