### ISSUE TITLE
Prendre en compte le cas commande position = position réelle

### ISSUE THREAD

**Issue by Ikes72000** [mika-nt28/Jeedom-voletProp#21]
Mika,

Peux prendre en compte le cas où la commande position envoyée à voletProp est déjà égale à la position?
Actuellement, quand ce cas se présente, le volet monte légèrement.

Merci.

**Comment by mika-nt28** [comment]
Ajouté

**Comment by Ikes72000** [comment]
Cool, merci. ;)
