### ISSUE TITLE
Rendre l'action de positionnement de l'objet volet utilisable plus facilement 

### ISSUE THREAD

**Issue by bastienjacquet** [mika-nt28/Jeedom-voletProp#41]
Dans les scenarios, ou en php, demander une valeur d'ouverture n'est pas facile. Il faut pour l'instant faire $options('_slider'=>75).

Je suis trop debutant Jeedom pour le faire ... pour l'instant ...

**Comment by mika-nt28** [comment]
Normalement tu sélectionne dans ton scénario la commande Hauteur et il te demandera de saisir la valeur que tu veux.

**Comment by bastienjacquet** [comment]
Est-ce que tu as testé?
Parce que "Hauteur" est une "info", pas une action.
L'action c'est "Position", [line 202](https://github.com/mika-nt28/Jeedom-voletProp/blob/3460719c00b70a48bb574e72b7797c3bd6833fc1/core/class/voletProp.class.php#L202) :
```
$hauteur=$this->AddCommande("Hauteur","hauteur","info",'numeric',0,null,null,null,'FLAP_STATE');
$this->AddCommande("Position","position","action",'slider',1,$hauteur->getId(),'Volet',null,'FLAP_SLIDER');
```
Et le execute ne passe que l'option 'slider', [Line 228](https://github.com/mika-nt28/Jeedom-voletProp/blob/3460719c00b70a48bb574e72b7797c3bd6833fc1/core/class/voletProp.class.php#L228) :
```
case "position":
	$this->getEqLogic()->execPropVolet($_options['slider']);
```

**Comment by mika-nt28** [comment]
Non je n'utilise pas se plugin je n'en ai pas besoin.
il est cree pour dépanner les gens

C'est effectivement Position qu'il faut utilisé et tu as raison je doit transmettre toutes l'option
Je corrige ça immédiatement
